environment:
  matrix:
    - PYTHON: "C:\\Python27"
      MAKE_WINEX: 0
    - PYTHON: "C:\\Python35"
      MAKE_WINEX: 1
    
install:
  - if %MAKE_WINEX%==1	%PYTHON%\Scripts\pip.exe install pyinstaller
  - '%PYTHON%\Scripts\pip.exe install .'

build_script:
  - if %MAKE_WINEX%==1	cd  scripts\for_pyinstaller
  - if %MAKE_WINEX%==1	%PYTHON%\Scripts\pyinstaller.exe nmrml2isa_cli.spec nmrml2isa_cli.py
  - cd ..\..\

test_script:
  - mkdir data
  - cd data
  - ps: wget http://ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/MTBLS1/ADG10003u_007.nmrML -O ADG10003u_007.nmrML
  - ps: wget http://ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/MTBLS1/ADG10003u_008.nmrML -O ADG10003u_008.nmrML
  - ps: Get-Content ADG10003u_007.nmrML -TotalCount 50
  - cd ..
  # Get ISA validator agents for validating 
  - ps: wget https://github.com/ISA-agents/ISAvalidator-ISAconverter-BIImanager/releases/download/1.6.5/ISA-validator-1.6.5.zip -o ISA-validator-1.6.5.zip
  - unzip ISA-validator-1.6.5.zip
  - ps: wget ftp://ftp.ebi.ac.uk/pub/databases/metabolights/submissionAgent/ISAcreatorMetaboLights.zip -o ISAcreatorMetaboLights.zip
  - unzip ISAcreatorMetaboLights.zip
  # Test using just python
  - "%PYTHON%\\python.exe -m nmrml2isa -i data -o out_folder\\metabolights -s MTBLS1"
  - java -cp ISA-validator-1.6.5\isaagents_deps.jar org.isaagents.isatab.manager.SimpleManager validate out_folder\metabolights\MTBLS1 Configurations\MetaboLightsConfig20140506\
  # test using the windows executable (no python requred)
  - if %MAKE_WINEX%==1	cd scripts\for_pyinstaller\dist\
  - if %MAKE_WINEX%==1	nmrml2isa_cli.exe -i ..\..\..\data\ -o out_folder\metabolights -s MTBLS1_exe
  - if %MAKE_WINEX%==1	java -cp ..\..\..\ISA-validator-1.6.5\isaagents_deps.jar org.isaagents.isatab.manager.SimpleManager validate out_folder\metabolights\MTBLS1_exe ..\..\..\Configurations\MetaboLightsConfig20140506\

artifacts:
   - path: scripts\for_pyinstaller\dist\nmrml2isa_cli.exe
     name: nmrml2isa_cli

deploy:
  provider: GitHub
  description: 'Release description'
  auth_token:
    secure: a1VIb788bLXA/fLgAoEJshK1aXtGdj79BNvzPg+YfAIrYhp6yaA4gJa6vp4BpWHS
  artifact: nmrml2isa_cli
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true